### ISSUE TITLE
Use 'squash and merge' PR style

### ISSUE THREAD

**Issue by tiran** [python-ldap/python-ldap#14]
The project is configured to use the default merge style. It creates merge commits. Can we use squash and merge instead to avoid merge commits?

**Comment by encukou** [comment]
It's not about configuration: GitHub allows choosing between between merge, squash, or rebase. It's about what the maintainers (currently: me) choose.

i either do a fast-forward push from the command line; or merge if that's not possible or the change is complex, and this works pretty well.

I'm against squashing being the *only* merge style: it would make more complex changes like https://github.com/python-ldap/python-ldap/pull/11 unreadable.

I can switch to only merging for complex changes (with nice isolated commits), and fast-forward or squash otherwise.

**Comment by tiran** [comment]
Yeah, that's perfect. For some PRs it makes sense to keep the full history. I'm happy as long as we can avoid github's default merge commits.

I'm closing the ticket with a 👍
