### ISSUE TITLE
Simple bind doesn't raise with empty password

### ISSUE THREAD

**Issue by OrangeDog** [python-ldap/python-ldap#174]
Issue description:
If you call simple_bind_s with an empty password, instead of raising an error it returns `tuple(97, [], 11, [])`. I don't know what that means, but `whoami_s()` continues to return `None`.

Steps to reproduce: 

    conn = ldap.initialize('ldaps://<server>:636')
    conn.simple_bind_s('foo', '')

Operating system: 
Windows 10 (1709 Build 16299.192)

Python version: 
v3.6.3 (2c5fed8)

python-ldap version: 
pyldap 2.4.45

**Comment by tiran** [comment]
python-ldap doesn't raise an exception, because your LDAP server does not return an error code. Instead it happily accepts the bind and returns a success result. ``97`` is the result type ``LDAP_RES_BIND``, ``11`` is the LDAP message id for the current connection.

The behavior of simple_bind depends on the configuration of your LDAP server. For example python-ldap's test instance of OpenLDAP is configured to reject empty binds. The operation ``l.simple_bind_s(self.server.root_dn, '')`` fails with ``UNWILLING_TO_PERFORM({'desc': u'Server is unwilling to perform', 'info': u'unauthenticated bind (DN with no password) disallowed'},)``. The operation ``l.simple_bind_s('foo', '')`` fails with ``INVALID_DN_SYNTAX({'desc': u'Invalid DN syntax', 'info': u'invalid DN'},)``. An empty bind ``l.simple_bind_s('', '')`` returns ``(97, [], 5, [])``.

**Comment by OrangeDog** [comment]
OK, thanks for explaining.
