### ISSUE TITLE
cannot be installed via pip3

### ISSUE THREAD

**Issue by nskalis** [python-ldap/python-ldap#175]
Hi,

I cannot install `python-ldap` library via pip3. Would you be so kind to advise please ?
```
# pip3 install python-ldap
Collecting python-ldap
  Using cached python-ldap-2.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t6aj0v83/python-ldap/setup.py", line 9, in <module>
        from ConfigParser import ConfigParser
    ImportError: No module named 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-t6aj0v83/python-ldap/
```

Steps to reproduce: 
```
yum groupinstall "Development tools"
yum install openldap-devel python-devel
pip3 install python-ldap
```

Operating system: 
```
# hostnamectl
   Static hostname: xxx
         Icon name: computer-vm
           Chassis: vm
        Machine ID: c6f7ceaf2b662447be72221a58fa173a
           Boot ID: 096b1c0d1c524504997b0c8185ca69d5
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.17.1.el7.x86_64
      Architecture: x86-64
```

Python version: 
```
# python3 --version
Python 3.4.5
```

python-ldap version: 
```
python-ldap (3.0.0b4)                                    - Python modules for implementing LDAP clients
```

**Comment by tiran** [comment]
You are trying to install ``python-ldap-2.5.2``, which is not compatible with Python 3.

**Comment by nskalis** [comment]
hmm.. what is the corresponding name of the library that is Python3 supported ?

**Comment by encukou** [comment]
Python3 support is still in beta. You need to pass --pre to make pip give
you the pre-release version:

pip install --pre python-ldap


On Feb 16, 2018 5:12 PM, "Nikos Skalis" <notifications@github.com> wrote:

hmm.. what is the corresponding name of the library that is Python3
supported ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/python-ldap/python-ldap/issues/175#issuecomment-366280047>,
or mute the thread
