### ISSUE TITLE
Providing Python wheels

### ISSUE THREAD

**Issue by bbc2** [python-ldap/python-ldap#191]
I noted in the documentation that wheels are not provided for this package.  Any reason not to, at least for Linux?  For instance, this makes the package hard to use on Heroku.

Otherwise, the package looks great.  Thank you for the hard work in supporting LDAP.  :)

**Comment by tiran** [comment]
We cannot provide Linux wheels because python-ldap is not compatible with manylinux1 wheel format. The library uses several external packages like OpenLDAP, SASL, Kerberos/GSSAPI, and OpenSSL. There is no stable ABI for the libraries.

We also don't offer Windows wheels because of complex dependencies.

**Comment by bbc2** [comment]
Ah, I see.  Thank you for the clarification!

**Comment by encukou** [comment]
We can't maintaint python-ldap wheels in a secure way.

**Comment by natefoo** [comment]
@tiran I may be misunderstanding the challenges but manylinux was designed for this very sort of scenario. It bundles all linked libraries unless they are part of a very small whitelist (e.g. libc) and rewrites the runtime linker search path so that the bundled libs are used instead of system libs. This should produce working binary wheels, with two potential downsides:

1. Modifications to dependencies made by the Linux distribution (such as a custom default path to OpenLDAP's config file, etc.) are not reflected in the wheel since it would likely use unmodified upstream versions. Additionally, the versions of client libs used in the wheel would need to be backwards compatible with potentially older server versions at the site, but most client/server libraries are pretty good about this.
2. What @encukou is mentioned is an issue, because you're bundling libs you do need to re-release wheels when there are security problems with the bundled libs. There are a few tools that automate the build process to make it somewhat easier, including [matthew-brett/multibuild](https://github.com/matthew-brett/multibuild) and [galaxyproject/starforge](https://github.com/galaxyproject/starforge), but they still require a manual process of following vulnerability disclosures and manually initiating new builds.

We've used starforge (full disclosure: a project we developed) to generate python-ldap wheels for [our pypiserver](https://wheels.galaxyproject.org/simple/python-ldap/), we're working on updating [the rule](https://github.com/galaxyproject/starforge/blob/461f11f80dd62b3f258f402e8568ceab5d6a6b53/wheels/build/wheels.yml#L50) to build the latest version, though.

**Comment by tiran** [comment]
I have never heard of starforge before. Thanks, it sounds like an interesting project.

I checked your build and found one big disadvantage for me. Your build does not support Kerberos. python-ldap without Kerberos/GSSAPI is pretty much pointless for anybody that works with Active Directory, FreeIPA, or other identity management systems. There are two Kerberos libraries: MIT and Heimdal. I don't think that a statically linked MIT Kerberos build would work properly on systems with Heimdal Kerberos.

OpenLDAP client library depends on a large amount of external dependencies, including OpenSSL, Cyrus SASL, GSSAPI, Kerberos, Linux Kernel Key Utils and SELinux. Here is a dump of my shared library:

```
$ ldd /usr/lib64/python3.7/site-packages/_ldap.cpython-37m-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007ffdcbb6a000)
        libldap_r-2.4.so.2 => /lib64/libldap_r-2.4.so.2 (0x00007fe386355000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007fe386343000)
        libpython3.7m.so.1.0 => /lib64/libpython3.7m.so.1.0 (0x00007fe385fc8000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe385fa6000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe385de0000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fe385dc6000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007fe385da5000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007fe385d0f000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007fe385a30000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fe3859f4000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fe3859ee000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fe3859e9000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe385863000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe386401000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fe385811000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fe385720000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fe385702000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fe3856fb000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fe3856e1000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fe3856cd000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fe3856c7000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fe38569a000)
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fe38560b000)
```

To be honest, I have no personal interest in spending any time on binary wheels. I also can't use any work time on the topic, because it does not make sense for my day job, either.

**Comment by natefoo** [comment]
Yeah, I use Heimdal myself so I'm familiar with the split. I believe Heimdal clients can talk to MIT KDCs, I'm not sure about the reverse, but it's possible that one lib could be chosen for the wheels and anyone who doesn't like that choice can always use the other by building python-ldap from source. Alternatively, you can follow the [psycopg2 example](http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/) and place the binaries under a separate name in PyPI so that people have to explicitly choose to get wheels.

If there was a repo maintained externally that built the wheels, would you be interested in publicizing those, and potentially allowing them to be uploaded to the official project in PyPI?

**Comment by encukou** [comment]
Publicizing? Definitely.

I'd be more careful about uploading to PyPI. I don't want people to just `pip install python-ldap` without having read any warnings in documentation.
The psycopg2 example looks more like a cautionary tale than a solution: `psycopg2-binary` will get you the wheel, but won't satisfy requirements on `psycopg2`. It's nice to allow *users* to choose between `psycopg2-binary` and `psycopg2`, but allowing *dependent packages* to make that choice isn't good.
