### ISSUE TITLE
Unable to install on Windows 10: fatal error C1083: Cannot open include file: 'lber.h'

### ISSUE THREAD

**Issue by AminMkh** [python-ldap/python-ldap#243]
Unable to install on Windows 10, I tried 
---
Issue description:
Whenever I run: `pip install python-ldap`
I get the following:
> c:\users\user\appdata\local\temp\pip-install-652a07b0\python-ldap\modules\constants.h(7): fatal error C1083: Cannot open include file: 'lber.h': No such file or directory
>     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
> 
>     ----------------------------------------
> Command ""c:\program files (x86)\python36-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-652a07b0\\python-ldap\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-09ceypm_\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-652a07b0\python-ldap\
> 

- I tried installing http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyldap:
`pip install pyldap-3.0.0-py2.py3-none-any.whl`
and got:
> pyldap-3.0.0-py2.py3-none-any.whl is not a supported wheel on this platform.

- Also looked into requirements: https://www.python-ldap.org/en/latest/installing.html#build-prerequisites
I downloaded the OpenLDAP client libs but didn't know where to place it's folder ?

Steps to reproduce: 
 `pip install python-ldap`

Operating system: Windows 10, version 1803, OS Build 171134.285
Python version:  Python 3.6.5

python-ldap version: None

Any ideas how to proceed ?

**Comment by encukou** [comment]
If you're using Christoph Gohlke's packages, you want to get [python-ldap](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-ldap), not pyldap.

**Comment by AminMkh** [comment]
yes I am trying either of them, same issue.

**Comment by tiran** [comment]
None of the python-ldap maintainers is a Windows developer. We all work on Linux or similar platforms and are unable to assist.

By the way, a python-ldap build with just OpenLDAP bindings is pretty much useless these days. You also need OpenSSL and libsasl. SASL also depends on Kerberos bindings. Good luck...

**Comment by encukou** [comment]
If you figure it out, please let us know so we can add some instructions to documentation.

**Comment by AminMkh** [comment]
thanks guys, will keep that in mind, however, if you are aware of any other packages to connect to Active Directory using Python 3 on Windows, please let me know.

**Comment by encukou** [comment]
I've heard of [ldap3](https://github.com/cannatag/ldap3), but never used it.

**Comment by AminMkh** [comment]
yes thanks @encukou , I tried it and it's working well, thank you.

**Comment by nickolay** [comment]
This issue is among the top results on Google for the 'lber.h' error. I felt I should mention that despite python-ldap maintainers not using Windows, the package has a non-trivial amount of people using it on Windows, judging from the stackoverflow activity.

While I didn't find up-to-date build instructions easily, there are prebuilt whl files that worked for me: 
https://stackoverflow.com/a/58235938/1026

**Comment by encukou** [comment]
We'd also welcome anyone interested in being a Windows maintainer, or just anyone who could write up better Windows build instructions for the documentation.

**Comment by pBogey** [comment]
> This issue is among the top results on Google for the 'lber.h' error. I felt I should mention that despite python-ldap maintainers not using Windows, the package has a non-trivial amount of people using it on Windows, judging from the stackoverflow activity.
> 
> While I didn't find up-to-date build instructions easily, there are prebuilt whl files that worked for me:
> https://stackoverflow.com/a/58235938/1026

Thanks, this also worked for me.

Using PyCharm, I must note that [this](https://github.com/pypa/pip/issues/5820) thread was also useful in upgrading pip.

**Comment by spinone** [comment]
I had all the same issues when trying to install windapsearch on Windows 10. Turns out that the Windows version of Python3 was 32 bit and the python-ldap module needed 64 bit. To find the architecture, I ran (using python3)
```import struct
print(struct.calcsize("P") * 8)```
I then installed the 32 bit version of python-ldap from [](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-ldap) . These are pre-compiled wheel files, which are installed as:
`pip install path\to\your.whl`
You may need to use <path-to-pip> for the python3 version

**Comment by kidjohnson** [comment]
Today i had the same issue running `pip install python-ldap`

```
fatal error C1083: Cannot open include file: 'lber.h': No such file or directory        
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
```
In my case, I was installing python-ldap because i needed django-auth-ldap, that requires python-ldap.

The **workaround** was to use [django-python3-ldap](https://github.com/etianen/django-python3-ldap) instead of django-auth-ldap.

**Comment by Torxed** [comment]
`Cannot open include file: 'lber.h': No such file or directory` is because you need the [OpenLDAP](https://www.openldap.org/) libraries installed on your system. So first step is to build those (or install them if you trust a pre-built binary).

Either way, building on windows is a PITA. Better use another library *or* a pre-built version linked from the official docs (and trust the trust chain in that the developers of python-ldap trusts whomever they link to).

**Comment by danielparla** [comment]
En mi caso tuve que instalar un bash de linux en mi equipo y ejecutar el comando de linux para la instalacion:
$ sudo apt-get install python-ldap
https://protegermipc.net/2018/08/15/instalar-bash-en-windows-10/

**Comment by peterwoo339** [comment]
> This issue is among the top results on Google for the 'lber.h' error. I felt I should mention that despite python-ldap maintainers not using Windows, the package has a non-trivial amount of people using it on Windows, judging from the stackoverflow activity.
> 
> While I didn't find up-to-date build instructions easily, there are prebuilt whl files that worked for me: https://stackoverflow.com/a/58235938/1026

this answer inspired me to fix the python-ldap installation failure on windows 11.
I was trying to install django-auth-ldap, but the installation errors suggested it was due to python-ldap could not be installed...
python-ldap whl can be found here https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-ldap
but, be noted that the key is to pick the right version of python-ldap package. By 'right', I mean, it has to go with your current python version.
Download that package, and run pip install <right version of python-ldap>.whl
then, installing django-auth-ldap went smoothly...
booyah! it worked for me anyway. hope it helps

**Comment by huths0lo** [comment]
> > This issue is among the top results on Google for the 'lber.h' error. I felt I should mention that despite python-ldap maintainers not using Windows, the package has a non-trivial amount of people using it on Windows, judging from the stackoverflow activity.
> > While I didn't find up-to-date build instructions easily, there are prebuilt whl files that worked for me:
> > https://stackoverflow.com/a/58235938/1026
> 
> Thanks, this also worked for me.
> 
> Using PyCharm, I must note that [this](https://github.com/pypa/pip/issues/5820) thread was also useful in upgrading pip.

Worked for me as well.  Thank you guys!

**Comment by DavyVos** [comment]
> well

I have tried installing python-ldap from this wheel as well, however I got the error:
```python
    from _ldap import *
ModuleNotFoundError: No module named '_ldap'
```
How would I go about fixing this issue? I expected the wheel to work without throwing issues. Is this an issue on my side?

**Comment by alokgupt68** [comment]
to install django-auth-ldap on windows, these are the only steps that you need to follow:
1)	First install Microsoft C++ build tools
Download the installer from: https://visualstudio.microsoft.com/visual-cpp-build-tools/  and run it.
2) Then you need to install python-ldap-3.4.4, for this you need to download the correct wheel file for your version of windows and python (run python –version, to see your version of python). This step will ensure that your system has the required OpenLDAP librairies and header files required for installation.
The wheel file can be downloaded from https://github.com/cgohlke/python-ldap-build/releases 
 OR https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-ldap
3)	Then run pip to install the wheel file (the wheel file should be copied to the directory of your virtual environment) for e.g.
(basel) D:\basel>pip install python_ldap-3.4.4-cp311-cp311-win_amd64.whl
4)	Finally install django-auth-ldap
(basel) D:\basel>pip install django-auth-ldap

**Comment by puigru** [comment]
For someone who already went to all the trouble of installing MSVC. Can anyone let us know where to place the OpenLDAP headers so that the build process can complete properly?
