### ISSUE TITLE
Python-LDAP+AD+Microsofr Security Advisory ADV190023

### ISSUE THREAD

**Issue by dkmstr** [python-ldap/python-ldap#309]
Hi, this is not an issue i think, but a question/request.
How does this affect to python-ldap when connecting to Active Directory usin LDAPS? (because i undertand that simple bind for LDAP will not be supported, and also have checked it :))

https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirement-for-windows

Thanks, 

P.D. I have set all the settings microsoft says, and simple_bind_s with LDAPS works fine, but don't know if this will change.

**Comment by tiran** [comment]
The support document is not about LDAPS but about LDAP with SASL. SASL provides authentication with optional data integrity and data encryption. You don't need SSL/TLS with SASL because SASL can protect and encrypt LDAP communication, too. It's commonly used with GSSAPI and GSSAPI SPNEGO (Kerberos).

At least older versions of AD do not support LDAPS + SASL encryption or LDAP + STARTTLS + SASL due to limitations in the crypto stack. This is totally fine because SASL already protects the data.

A SSF of 1 ensures data integrity, any SSF > 1 ensures data confidentiality. ``conn.set_option(ldap.OPT_X_SASL_SSF_MIN, 56)`` will give you at least 3DES, a value of 64 at least AES-128. Some servers miscalculate the SSF and consider AES-128 as SSF 56.

**Comment by dkmstr** [comment]
So, if i understand you, doing a simple_bind_s against AD after the fix will work using LDAPS with no problem, right?

Thanks! 👍

**Comment by ecki** [comment]
I tested simple binds over TLS and they will continue to work after setting required signing and channel binding. Simple binds without TLS won't work anymore when you require signing. (However this sounds not very secure and MS might sooner or later enable you to forbid simple binds).

**Comment by dkmstr** [comment]
My tests points to same. I have applied the settings and TLS (ldaps) 
works correctly as it's expected.

Thank you very much for all your help!

**Comment by tiran** [comment]
You are welcome!
