### ISSUE TITLE
Can python-ldap parse a captured LDAP response?

### ISSUE THREAD

**Issue by PenelopeFudd** [python-ldap/python-ldap#475]
## Issue description:

I'm trying to debug an application that's sending requests to our LDAP server (TLS off while debugging), as it's not authenticating users, its terminology is not standard (AFAICT), and it's not printing a useful error message.

What I'm trying to do is to convert a tcpdump capture of the request and response into an equivalent `ldapsearch` command, and I've gotten part way there with bash, calling tshark to reassemble the conversation, then OpenSSL's asn1parse to translate that into human-readable (barely) tokens, and then using awk to translate that into an equivalent `ldapsearch` command.

I've discovered that awk is in no way suited for the task, and so I'm looking to switch to python-ldap.

I've read through the documentation and test cases lightly but could not see a way to use python-ldap to parse an already-captured string, but that's probably because I'm not a Python expert.

Is there a way already, or is this a feature request?

At the moment, looking at wireshark dissections of the request is all I've got, and it's hard to translate that to ldapsearch commands.

Thanks!

## Steps to reproduce: 
1. Capture packets: `tcpdump -w d.cap -i any port 389`
2. Reconstruct stream: `tshark -r d.pcap -q -z follow,tcp,raw,0 | gawk 'BEGIN{cmd="xxd -p -r"};NR>6 && !/^=/{print $1 | cmd;close(cmd)}' > d.bin`
3. Parse stream with python-ldap: `my-parser.py d.bin`
4. Print `ldapsearch -D $binddn -w '$password' -b $basedn -s $scope $other_options $filter $attributes`

### Operating system: 
Ubuntu

### Python version: 
Python3

### python-ldap version: 
n/a

**Comment by mistotebe** [comment]
Wireshark/tshark might be able to give you what you need since it has the relevant LDAP dissectors and supports some LUA scripting. That scripting is even supposed to be able to read the information after the dissector has done its work.

The python-ldap modules don't expose any parts of liblber which is what you'd need (plus some programming) to disassemble the stream manually. If your server is OpenLDAP, its logs might give you a better insight, you can also use the accesslog overlay, logging all including unsuccessful operations.

If your server isn't OpenLDAP, you might still be to configure it as a proxy to your actual LDAP server.

**Comment by PenelopeFudd** [comment]
Ok, thank you; that helps a bunch!

**Comment by PenelopeFudd** [comment]
https://ask.wireshark.org/question/27350/is-it-possible-to-decode-ldap-as-ldapsearch-command/
